const express=require('express')
const User = require('../models/userModel')
const router=express.Router()
const authController=require('../controllers/authContoller')
const { identifier } = require('../middlewares/identification')
router.post('/signup',authController.signUp)
router.post('/signin',authController.signin)
router.post('/signout',identifier,authController.signout)
router.patch('/send-verification-code',identifier,authController.sendVerificationCode)
router.patch('/verify-code',identifier,authController.verifyVerifcationCode)
router.patch('/change-password',identifier,authController.changePassword)
router.patch('/send-forgot-password-code',authController.sendForgotPasswordCode)
router.patch('/verify-forgot-password',authController.verifyPasswordCode)
module.exports=router